GET http://localhost:5000/api/chatbot/chats

###

GET http://localhost:5000/api/chatbot/chats/1

###

PUT http://localhost:5000/api/chatbot/chats/1
Content-Type: application/json

{
  "title": "Chat Edit 1"
}

###

DELETE http://localhost:5000/api/chatbot/chats/4

###

GET http://localhost:5000/api/chatbot/chats/1/messages

###

POST http://localhost:5000/api/chatbot/chats/1/messages
Content-Type: application/json

{
  "prompt": "Berapa hasil 1 + 5"
}