GET http://localhost:5000/api/chatbot/chats

###

GET http://localhost:5000/api/chatbot/chats/1/messages

###

POST http://localhost:5000/api/chatbot/chats/1/messages
Content-Type: application/json

{
  "prompt": "Berapa hasil 1 + 5"
}