GET http://localhost:5000/todos

###

GET http://localhost:5000/todos/1

###

POST http://localhost:5000/todos
Content-Type: application/json

{
  "user_id": 1,
  "title": "New Todo",
  "description": "Description of the new todo",
  "due_date": "2023-12-31",
  "is_completed": 0
}

###

DELETE http://localhost:5000/todos/5

###

PUT http://localhost:5000/todos/3
Content-Type: application/json

{
  "password": "newsecurepassword"
}
